# DAT210x - Programming with Python for DS

## Module2 - Lab5

Import and alias Pandas:

In [6]:
# .. your code here ..
import pandas as pd
df=pd.read_csv('/home/rahul/Desktop/data_science/EDX_Data_Science/jupyter/module_2_DATA_warangling/Datasets/census.data',header=-1)
df.columns=['Sno','education', 'age', 'capital-gain', 'race', 'capital-loss', 'hours-per-week', 'sex', 'classification']
df

,Sno,education,age,capital-gain,race,capital-loss,hours-per-week,sex,classification
0,0,Bachelors,39,2174,White,0,40,Male,<=50K
1,1,Bachelors,50,?,White,0,13,Male,<=50K
2,2,HS-grad,38,?,White,0,40,Male,<=50K
3,3,11th,53,?,Black,0,40,Male,<=50K
4,4,Bachelors,28,0,Black,0,40,Female,<=50K
5,5,Masters,37,0,White,0,40,Female,<=50K
6,6,9th,49,0,Black,0,16,Female,<=50K
7,7,HS-grad,52,0,White,0,45,Male,>50K
8,8,Masters,31,14084,White,0,50,Female,>50K
9,9,Bachelors,42,5178,White,0,40,Male,>50K
10,10,Some-college,37,0,Black,0,80,Male,>50K
11,11,Bachelors,30,0,Asian-Pac-Islander,0,40,Male,>50K
12,12,Bachelors,23,0,White,0,30,Female,<=50K
13,13,7th-8th,34,0,Amer-Indian-Eskimo,0,45,Male,<=50K
14,14,HS-grad,25,0,White,0,35,Male,<=50K
15,15,HS-grad,32,0,White,0,40,Male,<=50K
16,16,11th,38,0,White,0,50,Male,<=50K
17,17,Masters,43,0,White,0,45,Female,>50K
18,18,Doctorate,40,0,White,0,60,Male,>50K
19,19,HS-grad,54,0,Black,0,20,Female,<=50K
20,20,9th,35,0,Black,0,40,Male,<=50K
21,21,11th,43,0,White,2042,40,Male,<=50K
22,22,HS-grad,59,0,White,0,40,Female,<=50K
23,23,Bachelors,56,0,White,0,40,Male,>50K
24,24,HS-grad,19,0,White,0,40,Male,<=50K
25,25,Some-college,54,0,Asian-Pac-Islander,0,60,Male,>50K
26,26,HS-grad,39,0,White,0,80,Male,<=50K
27,27,HS-grad,49,0,White,0,40,Male,<=50K
28,28,Some-college,20,0,Black,0,44,Male,<=50K
29,29,Bachelors,45,0,White,1408,40,Male,<=50K
...,...,...,...,...,...,...,...,...,...
29506,29506,HS-grad,30,0,White,0,55,Male,<=50K
29507,29507,10th,32,0,White,0,40,Male,<=50K
29508,29508,Some-college,22,0,White,0,40,Male,<=50K
29509,29509,HS-grad,31,0,White,0,40,Female,<=50K
29510,29510,HS-grad,29,0,White,0,35,Female,<=50K
29511,29511,Bachelors,35,0,White,0,55,Female,>50K
29512,29512,Bachelors,30,0,Asian-Pac-Islander,0,99,Female,<=50K
29513,29513,Doctorate,34,0,White,0,60,Male,>50K
29514,29514,Bachelors,54,0,Asian-Pac-Islander,0,50,Male,>50K
29515,29515,Some-college,37,0,White,0,39,Female,<=50K
29516,29516,12th,22,0,Black,0,35,Male,<=50K
29517,29517,Bachelors,34,0,White,0,55,Female,>50K
29518,29518,HS-grad,30,0,Black,0,46,Male,<=50K
29519,29519,Bachelors,38,15020,Black,0,45,Female,>50K
29520,29520,Doctorate,71,0,White,0,10,Male,>50K
29521,29521,HS-grad,45,0,White,0,40,Female,<=50K
29522,29522,HS-grad,41,0,Black,0,32,Female,<=50K
29523,29523,HS-grad,72,0,White,0,25,Male,<=50K
29524,29524,Masters,31,0,Other,0,30,Female,<=50K
29525,29525,HS-grad,43,0,White,0,40,Male,<=50K
29526,29526,Some-college,43,0,White,0,40,Female,<=50K
29527,29527,Some-college,43,0,White,0,50,Male,<=50K
29528,29528,10th,32,0,Amer-Indian-Eskimo,0,40,Male,<=50K
29529,29529,Masters,32,0,Asian-Pac-Islander,0,11,Male,<=50K
29530,29530,Masters,53,0,White,0,40,Male,>50K
29531,29531,Some-college,22,0,White,0,40,Male,<=50K
29532,29532,HS-grad,40,0,White,0,40,Male,>50K
29533,29533,HS-grad,58,0,White,0,40,Female,<=50K
29534,29534,HS-grad,22,0,White,0,20,Male,<=50K
29535,29535,HS-grad,52,15024,White,0,40,Female,>50K

As per usual, load up the specified dataset, setting appropriate header labels.

In [ ]:
# .. your code here ..

Excellent.

Now, use basic pandas commands to look through the dataset. Get a feel for it before proceeding!

Do the data-types of each column reflect the values you see when you look through the data using a text editor / spread sheet program? If you see `object` where you expect to see `int32` or `float64`, that is a good indicator that there might be a string or missing value or erroneous value in the column.

In [24]:
# .. your code here ..
import pandas as pd
df=pd.read_csv('/home/rahul/Desktop/data_science/EDX_Data_Science/jupyter/module_2_DATA_warangling/Datasets/census.data',header=-1)
df.columns=['Sno','education', 'age', 'capital-gain', 'race', 'capital-loss', 'hours-per-week', 'sex', 'classification']
df['capital-gain'].unique()
df['capital-gain']=pd.to_numeric(df['capital-gain'],errors='coerce')
df['capital-gain']=df['capital-gain'].fillna(0)
#df.dtypes
df[['age']]
df.age

0        39
1        50
2        38
3        53
4        28
5        37
6        49
7        52
8        31
9        42
10       37
11       30
12       23
13       34
14       25
15       32
16       38
17       43
18       40
19       54
20       35
21       43
22       59
23       56
24       19
25       54
26       39
27       49
28       20
29       45
         ..
29506    30
29507    32
29508    22
29509    31
29510    29
29511    35
29512    30
29513    34
29514    54
29515    37
29516    22
29517    34
29518    30
29519    38
29520    71
29521    45
29522    41
29523    72
29524    31
29525    43
29526    43
29527    43
29528    32
29529    32
29530    53
29531    22
29532    40
29533    58
29534    22
29535    52
Name: age, dtype: int64

Try use `your_data_frame['your_column'].unique()` or equally, `your_data_frame.your_column.unique()` to see the unique values of each column and identify the rogue values.

If you find any value that should be properly encoded to NaNs, you can convert them either using the `na_values` parameter when loading the dataframe. Or alternatively, use one of the other methods discussed in the reading.

In [ ]:
# .. your code here ..

Look through your data and identify any potential categorical features. Ensure you properly encode any ordinal and nominal types using the methods discussed in the chapter.

Be careful! Some features can be represented as either categorical or continuous (numerical). If you ever get confused, think to yourself what makes more sense generally---to represent such features with a continuous numeric type... or a series of categories?

In [ ]:
# .. your code here ..

Lastly, print out your dataframe!

In [ ]:
# .. your code here ..